name: CI

"on": [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for metadata
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Python install
        run: |
          python -m pip install --upgrade pip
          python -m pip install "lander<2.0.0"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: sqrereadonly
          password: ${{ secrets.DOCKERHUB_SQREREADONLY_TOKEN }}

      - name: TeX build
        run: |
          docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'

      - name: Landing page upload
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          lander --upload --pdf DMTN-292.pdf --ltd-product dmtn-292 --lsstdoc "DMTN-292.tex" --author "Frossie Economou" --author "Michael J. Reuter" --author "Russ Allbery" --author "Christine Banek" --author "Angelo Fausti Neto" --author "Jonathan Sick" --author "Adam J. Thornton" --abstract "In order to address the challenges of the Rubin Science Platform, Rubin developed a kubernetes-based approach to service deployment with an in-house service configuration and support infrastructure called phalanx, based on ArgoCD. It became apparent that the challenges of running a service-oriented architecture in a modern observatory summit lent themselves equally well to this approach. In this talk we will describe how phalanx was adapted for use for telescope, instrument and sensor control services and the advantages of providing a unified service infrastructure for both control systems and data services."
